# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl')], default='boy', max_length=16)),
                ('portrait', models.FileField(upload_to='documents/portrait')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('qr', models.FileField(upload_to='documents/project/qr')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='applyform',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrontSystem.Project'),
        ),
    ]
