# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FrontSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('qr', models.FileField(blank=True, null=True, upload_to='statics/documents/project/qr')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='price',
        ),
        migrations.RemoveField(
            model_name='project',
            name='qr',
        ),
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_at',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_at',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='portrait',
            field=models.FileField(blank=True, null=True, upload_to='statics/documents/portrait'),
        ),
        migrations.AddField(
            model_name='applyform',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FrontSystem.Classes'),
        ),
    ]
