# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyform',
            name='portrait',
            field=models.FileField(blank=True, null=True, upload_to='documents/portrait'),
        ),
        migrations.AlterField(
            model_name='project',
            name='qr',
            field=models.FileField(blank=True, null=True, upload_to='documents/project/qr'),
        ),
    ]
